language: r
r: bioc-devel
sudo: TRUE

env:
  global:
    - MAKEFLAGS="-j 2"

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libv8-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - R -q -e 'install.packages(c("BH", "Rcpp", "RcppEigen",
                                "StanHeaders", "rstantools",
                                "rstan", "covr"))'
  - mkdir -p ~/.R/
  - echo "CXX14 = g++-7 -fPIC -flto=2" >> ~/.R/Makevars
  - echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

script:
  - travis_wait 40 R CMD build
  - R CMD check *tar.gz

after_script:
  - tar -ztvf cytoeffect_*.tar.gz
  - echo ${NOT_CRAN}

after_success:
  - R -q -e 'covr::codecov()'

after_failure:
  - cat cytoeffect_*.failure.txt
