language: r
os: linux
dist: xenial

cache:
  - packages
  - ccache

warnings_are_errors: FALSE

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

before_install:
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -march=native -mtune=native -fPIC" >> ~/.R/Makevars
  - echo "CXX14=g++" >> ~/.R/Makevars

after_success:
  - travis_wait 40 Rscript -e 'covr::codecov()'

after_failure:
  - travis_wait 40
