language: r
sudo: false
cache: packages

latex: true

env:
  global:
    - MAKEFLAGS="-j 2"

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libv8-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

# for code coverage
r_packages:
  - covr

before_install:
  - mkdir -p ~/.R/
  - echo "CXX14 = g++-7 -fPIC -flto=2" >> ~/.R/Makevars
  - echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars

install:
  - R -e "install.packages('rstan', repos = 'https://cloud.r-project.org/', dependencies = TRUE)"
  - R -e "install.packages('devtools', repos = 'https://cloud.r-project.org/', dependencies = TRUE)"
  - R -e 'devtools::install_deps(dep = T)'

script:
  - R -e "rstan::stan_version()"
  - R CMD build --no-build-vignettes --as-cran .
  - R CMD check --no-vignettes --no-build-vignettes cytoeffect_*.tar.gz

after_script:
  - tar -ztvf cytoeffect_*.tar.gz
  - echo ${NOT_CRAN}

after_success:
  - Rscript -e 'covr::codecov()'
