language: r
os: linux
dist: xenial

cache:
  - packages
  - ccache

warnings_are_errors: FALSE

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

# currently there is a bug in rstantools 2.1.0 (tbb header missing)
before_install:
  - Rscript -e 'install.packages("remotes")'
  - Rscript -e 'remotes::install_version("rstantools", version = "2.0.0", repos = "http://cran.us.r-project.org")'
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -march=native -mtune=native -fPIC" >> ~/.R/Makevars
  - echo "CXX14=g++" >> ~/.R/Makevars

after_success:
  - travis_wait 40 Rscript -e 'covr::codecov()'

# voids Job log truncation
after_failure:
  - travis_wait 40
